{
    "target":[
        {
            "target_name":"default",
            "ref_asm":[
                "Newtonsoft.Json.dll"
            ],
            "lnk_files":[

            ],
            "ref_packs":[

            ],
            "recipes":[
                {
                    "recipe_name":"default",
                    "command_only":false,
                    "recipe_data":[
                        {
                            "command":"sudo",
                            "arguments":"mkbundle build/smake.exe build/Newtonsoft.Json.dll -o /bin/smake",
                            "is_post":true
                        },
                        {
                            "command":"sudo",
                            "arguments":"chmod +x /bin/smake",
                            "is_post":true
                        }
                    ]
                }
            ],
            "output":"smake",
            "output_type":"exe",
            "unsafe_code":false,
            "platform":"any",
            "code_root":"code/",
            "lib_dir":"libs/",
            "output_dir":"build/",
            "sequencial_naming":false
        },
        {
            "target_name":"clean",
            "recipes":[
                {
                    "recipe_name":"clean",
                    "command_only":true,
                    "recipe_data":[
                        {
                            "command":"smake",
                            "arguments":"--clean",
                            "is_post":true
                        }
                    ]
                }
            ]
        },
        {
            "target_name":"full",
            "recipes":[
                {
                    "recipe_name":"full",
                    "command_only":true,
                    "recipe_data":[
                        {
                            "command":"smake",
                            "arguments":"",
                            "is_post":true
                        },
                        {
                            "command":"smake",
                            "arguments":"clean",
                            "is_post":true
                        }
                    ]
                }
            ]
        }
    ]
}
